# Generated by Django 3.2.7 on 2022-01-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpha', '0002_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='imgcaption',
            field=models.CharField(default='Profile Picture', max_length=230),
        ),
    ]
